#include <stdio.h>

#define auto      automático
#define break     interrupción
#define case      caso
#define char      carácter
#define const     constante
#define continue  continuar
#define default   por_defecto
#define do        hacer
#define double    doble
#define else      sino
#define enum      enumeración
#define extern    externo
#define float     flotante
#define for       para
#define goto      ir_a
#define if        si
#define int       entero
#define long      largo
#define register  registro
#define return    retornar
#define short     corto
#define signed    firmado
#define sizeof    tamaño_de
#define static    estático
#define struct    estructura
#define switch    cambiar
#define typedef   typedef
#define union     unión
#define unsigned  sin_signo
#define void      vacío
#define volatile  volátil
#define while     mientras

#define include incluir


#define imprimir printf
#define escanear scanf
#define abrir fopen
#define cerrar fclose
#define leer fread
#define escribir fwrite
#define buscar strchr
#define copiar strcpy
#define concatenar strcat
#define comparar strcmp
#define asignar malloc
#define liberar free
#define redimensionar realloc
#define concatenar_string snprintf
#define longitud_string strlen
#define convertir_entero atoi
#define convertir_flotante atof
#define obtener_hora localtime
#define obtener_tiempo time
#define obtener_caracter getchar
#define mostrar_caracter putchar
#define salida_estandar stdout
#define entrada_estandar stdin
